### ISSUE TITLE
Resources for running InstantWM outside of InstantOS?

### ISSUE THREAD

**Issue by Veraellyunjie** [instantOS/instantWM#120]
Is there any forum and wiki or something similar dedicated to running Instant environment outside of InstantOS?

Your presentation videos really hooked me in, and I have installed InstantWM on OpenBSD, but a lot of functionality is missing.
Yes, InstantOS is more than InstantWM, but
1. Some things I believe should work in the InstantWM alone, but they don't;
2. A guide on which parts to install and how to configure them would be nice.

If there is such a resource please direct me thither.
If not, are there any plans on creating such a resource, be it by the InstantOS author or community?

---

My most urgent problems are:

* [build.sh](https://github.com/instantOS/instantWM/blob/main/build.sh) uses `make`, but BSD `make` is incompatible with GNU `make` and exits with an error. Please mention that you need `gmake` on *BSD.

* that long string, probably version, on the right of the bar. There probably is no need for it there, even if it didn't make tray and clock disappear. Why is it there at all?
![instantwm](https://user-images.githubusercontent.com/75799052/148699211-5b34c218-628d-4971-8ff2-ce4d0f5e6ad7.png)
 
* tag icons are missing

* taskbar icons? Those multi-color ones?

* each wm action (switch/move to a workspace; resize a window; switch the mode; etc.) entails an immediate brief disk activity, as if InstantWM writes something into a file. It gets on my nerves. Can the instantwm's behaviour be altered in this regard?
In case it is done for preserving the state of all the windows, I don't mind losing it.

* `st` doesn't launch via shortkey although it is installed and does launch manually

* hotkeys to navigate windows as they are displayed? Switch to the window to the right/left/up/down; in addition to cycling through all of them?

* hotkeys to navigate windows as they are shown on the taskbar? Similar to how you switch to right/left browser tab with ^PgUp/^PgDn and move them with ^⇧PgUp/^⇧PgDn…

* With windows maximized, Iridium (Chromium) browser has a border regardless of its preference `Use system title bar and borders` on/off.
I believe there is no your fault but maybe you know how to get rid of those borders.

* how to switch on blur?

* how to befriend a third-party panel, say `tint2`?

Thank you, your InstantWM and tools are very promising.

**Comment by con-f-use** [comment]
> Is there any forum and wiki or something similar dedicated to running Instant environment outside of InstantOS?

No. It's not really benni's focus. Also this would be a rabbit hole, because making it work on every possible system is a job for a whole team of people not one and a half part-timers. But the discord is pretty active and you'll find nice people with similar goals there.

> My most urgent problems are:
> 
>     * [build.sh](https://github.com/instantOS/instantWM/blob/main/build.sh) uses `make`, but BSD `make` is incompatible with GNU `make` and exits with an error. Please mention that you need `gmake` on *BSD.

BSD is pretty niche and it should be pretty obvious which version of make is used.
 
>     * that long string, probably version, on the right of the bar. There probably is no need for it there, even if it didn't make tray and clock disappear. Why is it there at all?

It's the complete version string. It is there because it's the fallback if `instantstatus` did not update the status bar.

>     * tag icons are missing

That's because you don't have the proper fonts installed.
 
>     * taskbar icons? Those multi-color ones?

No idea what you're talking about.

>     * each wm action (switch/move to a workspace; resize a window; switch the mode; etc.) entails an immediate brief disk activity, as if InstantWM writes something into a file. It gets on my nerves. Can the instantwm's behaviour be altered in this regard?

It really doesn't. Please be more specific, might be something about your X window or system in general.

>     * `st` doesn't launch via shortkey although it is installed and does launch manually

Probably because iconf is used to detect the terminal. What's the content of `~/.config/instantos/default/`. Should be something like:
![image](https://user-images.githubusercontent.com/11145016/148702722-f64801ea-ba70-44f3-bd91-bce6996ef62a.png)
 
>     * hotkeys to navigate windows as they are displayed? Switch to the window to the right/left/up/down; in addition to cycling through all of them?

Something I would like to see as well.

>     * how to switch on blur?

Instantsettings
![image](https://user-images.githubusercontent.com/11145016/148702838-f7618374-8b32-419e-a945-014fa6cfc664.png)

Please keep in mind that github is a platform for development and issues are supposed to be narrow-scoped and specific, not a wish list. This would have been better in any of the other media on the [support page](https://instantos.io/support).
