### ISSUE TITLE
make clean doesn't remove config.h

### ISSUE THREAD

**Issue by XeroOl** [instantOS/instantWM#51]
The command `make clean` should remove the `config.h` file, but it doesn't. This is an issue with the Makefile. I can't tell why this isn't happening, because the Makefile makes it seem like this should get deleted.

![image](https://user-images.githubusercontent.com/6820998/100686111-48ac2a00-3343-11eb-8c2f-98e33b572a85.png)

**Comment by con-f-use** [comment]
The Makefile is quit clear about, what it removes
```
OBJ = ${SRC:.c=.o}
# ...
clean:
	rm -f instantwm ${OBJ} instantwm-${VERSION}.tar.gz
```
I don't think it shoul remove `config.h` because that is user edited code, that might still be needed. The convention is, that `make clean` only removes build artifacts and files auto-generated by the build system. You will find that, in accordance with this convention, none of the suckless tools' `clean` rules remove that file either.

**Comment by XeroOl** [comment]
Thanks for clearing this up. I've been editing `config.def.h` with my settings for a while now, but now I understand the convention.
