### ISSUE TITLE
Feature: Independent master/slave layouts

### ISSUE THREAD

**Issue by UserXGnu** [instantOS/instantWM#80]
It would be perfect if the master and the slave area could have independent layouts.

 It would create a lot of freedom specially for those with ultra wide monitors. With the layouts we have right now, if you have a  ultra wide monitor you can't really  make a good use of the real state size of the it.

In the end you have huge wide windows that just take too much space.

Examples:

| Master |  Slave |
|:---:|:---:|
|   +       |     #     |
|  [  ]      |     =    |
|   =       |     &#124;&#124;&#124;   |
|   ...      |    ...     |

**Comment by con-f-use** [comment]
You're welcome to implement another layout more suited to wide screens here: https://github.com/instantOS/instantWM/blob/master/layouts.c

Having two different layouts in the master and slave area would create too much confusion and edge-cases, I think, both on the implementation- and user-side of things.

**Comment by paperbenni** [comment]
Many layouts don't function without a master and stack area (and they'd break if you make them be "in the master area") so what you are actually asking for is recursive layouts which would be a whole different endeavour and also confusing and complicated to use. I agree with confuse here that we should probably just create a wide screen specific layout. The floating layout is probably also suitable for large screens since maximizing screen real estate isn't as much of a priority
